Bluetooth
frc2052/FRC-Krawler pull request #71
Opened 2021-03-02 00:16 UTC by matth77

Added basic bluetooth capabilities and limited configuration.

2021-03-02 01:16 UTC, bherbst commented
Can you edit your PR and change the base branch from `main` to `mainV4`?

2021-03-02 01:44 UTC, bherbst requested changes

2021-03-02 01:44 UTC, bherbst commented on app/src/main/java/com/team2052/frckrawler/bluetooth/BluetoothCapabilities.kt
> +class BluetoothCapabilities(private val context: Context, private val bluetoothAdapter: BluetoothAdapter? = BluetoothAdapter.getDefaultAdapter(), var bluetoothState: BluetoothState = BluetoothState.B
Not super important for this PR, but in general a good formatting to follow to keep things readable when you have multiple constructor arguments is to put each one on a new line. For example:

```kotlin
class BluetoothCapability(
  private val context: Context,
  private val bluetoothAdapter: BluetoothAdapter
) : BroadcastReceiver() {
  // ...
}
```

2021-03-02 01:44 UTC, bherbst commented on app/src/main/java/com/team2052/frckrawler/bluetooth/BluetoothCapabilities.kt
> +    {
Tell Scott to keep his curly brace formatting out of here!

But seriously- we should follow Kotlin standards and keep opening curly braces inline with the method signature. The format command in Android Studio should do that automatically!

2021-03-02 01:44 UTC, bherbst commented on app/src/main/java/com/team2052/frckrawler/bluetooth/BluetoothCapabilities.kt
> +    {
Side note- I can look into having GitHub automatically apply formatting so we don't need to worry about it

2021-03-02 01:44 UTC, bherbst commented on app/src/main/AndroidManifest.xml
> +
I actually don't think you need this at all. `BroadcastReceiver` has changed a lot over the years, so I'm not surprised to see this around, but with the style you are using (calling `context.registerReceiver()`) you shouldn't need the manifest entry.

2021-03-02 01:44 UTC, bherbst commented on app/src/main/java/com/team2052/frckrawler/bluetooth/configuration/client/BluetoothClientConfiguration.kt
> +class BluetoothClientConfiguration : BluetoothConfiguration()
Your build is currently failing because this class needs to implement the `close()` method:
https://github.com/frc2052/FRC-Krawler/runs/2008875160?check_suite_focus=true#step:5:57

2021-03-02 01:44 UTC, bherbst commented on app/src/main/res/layout/bluetooth_connecting_fragment.xml
> +            android:text="Hello"
Did you mean to keep this "Hello"?

2021-03-02 01:44 UTC, bherbst commented on app/src/main/res/layout/bluetooth_connecting_fragment.xml
> +            android:id="@+id/button2"
Would love to see a more descriptive ID here!

2021-03-25 15:53 UTC, matth77 commented
Closing for better one

2021-03-25 15:53 UTC, closed without merging